# Generated by Django 2.1.1 on 2019-12-23 07:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nasrulhifz.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nasrulhifz', '0002_quranmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurahMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.SmallIntegerField()),
                ('name_string', models.CharField(max_length=100)),
                ('surah_ayat_max', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hifz',
            name='average_difficulty',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hifz',
            name='hafiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hifz',
            name='juz_number',
            field=models.SmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hifz',
            name='last_refreshed',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='quranmeta',
            name='juz_number',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordindex',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(nasrulhifz.models.DifficultyChoice(3), 3), (nasrulhifz.models.DifficultyChoice(2), 2), (nasrulhifz.models.DifficultyChoice(1), 1)], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quranmeta',
            name='ayat_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='quranmeta',
            name='surah_number',
            field=models.SmallIntegerField(),
        ),
    ]
