# Generated by Django 2.2.4 on 2020-04-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasrulhifz', '0003_auto_20191223_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glyphs',
            fields=[
                ('glyph_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('page_number', models.IntegerField()),
                ('line_number', models.IntegerField()),
                ('sura_number', models.IntegerField()),
                ('ayah_number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('min_x', models.IntegerField()),
                ('max_x', models.IntegerField()),
                ('min_y', models.IntegerField()),
                ('max_y', models.IntegerField()),
            ],
            options={
                'db_table': 'glyphs',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='hifz',
            name='revised_count',
            field=models.IntegerField(default=1, verbose_name='Revised Count'),
        ),
    ]
