# Generated by Django 2.2.4 on 2020-01-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20200114_1649"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogcategory", name="icon",),
    ]
