# Generated by Django 2.0.2 on 2018-07-31 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hifz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.SmallIntegerField()),
                ('ayat_number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WordIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField()),
                ('hifz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qurandata.Hifz')),
            ],
        ),
    ]
